name: '$name'
description: 'Emit Light from Held Items using the 1.20 Light Blocks.'
website: 'https://github.com/Mvndi/DynamicLights'
authors: [ 'xCykrix', 'Hydrolien' ]
version: $version

main: github.xCykrix.dynamicLights.DynamicLights
api-version: "$apiVersion"
load: 'POSTWORLD'
folia-supported: true

permissions:
  dynamiclights.lock:
    description: "Toggle placing light sources from your off hand."
    default: false
  dynamiclights.toggle:
    description: "Toggle rendering of light sources for your client."
    default: true
  dynamiclights.reload:
    description: "Reload the lights.yml configuration file."
    default: op